const fs = require('fs');

let dataJs = fs.readFileSync('SIGMA_SIM/js/data.js', 'utf8');

if (!dataJs.includes('function printAIReport')) {
    dataJs += `

// ── [신규] AI 리포트 인쇄/PDF 출력 함수 ──
function printAIReport() {
    if (!window.__lastAIReportHTML) {
        alert('리포트 데이터가 없습니다. 먼저 분석을 진행해주세요.');
        return;
    }
    
    const printWindow = window.open('', '_blank', 'width=850,height=900');
    if (!printWindow) {
        alert('팝업이 차단되었습니다. 브라우저 설정에서 팝업을 허용해주세요.');
        return;
    }
    
    printWindow.document.write(\`
        <!DOCTYPE html>
        <html>
        <head>
            <title>SIGMA AI Report - \${window.__lastAIReportTitle}</title>
            <meta charset="utf-8">
            <style>
                @import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css');
                body {
                    font-family: 'Pretendard', -apple-system, sans-serif;
                    line-height: 1.6;
                    color: #222;
                    padding: 40px;
                    background: #fff;
                    margin: 0 auto;
                    max-width: 900px;
                }
                h1, h2, h3 { color: #111; margin-top: 1.5em; border-bottom: 2px solid #ddd; padding-bottom: 8px; }
                h4 { color: #444; margin-top: 1.2em; }
                table {
                    width: 100%;
                    border-collapse: collapse;
                    margin: 25px 0;
                    font-size: 13px;
                }
                th, td {
                    border: 1px solid #ccc;
                    padding: 10px 14px;
                    text-align: left;
                }
                th {
                    background-color: #f8f9fa;
                    font-weight: 700;
                    color: #000;
                }
                li { margin-bottom: 6px; }
                strong { color: #000; font-weight: 800; background: rgba(255,183,77,0.2); padding: 0 4px; border-radius: 2px; }
                
                .report-header { text-align: center; margin-bottom: 50px; }
                .report-header h1 { border: none; margin-bottom: 10px; font-size: 28px; }
                .report-header .meta { color: #666; font-size: 14px; }
                .footer { margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; font-size: 11px; color: #999; text-align: center; }
                
                @media print {
                    body { padding: 0; max-width: none; }
                    @page { margin: 15mm; }
                    button { display: none; }
                }
            </style>
        </head>
        <body>
            <div class="report-header">
                <h1>교통 신호운영 통계 분석 리포트</h1>
                <div class="meta">\${window.__lastAIReportTitle} | Generated by SIGMA AI Platform</div>
            </div>
            
            \${window.__lastAIReportHTML}
            
            <div class="footer">
                이 보고서는 SIGMA 플랫폼의 거시적 교통 데이터와 Gemini AI 모델을 활용하여 자동 생성되었습니다.<br>
                보고서에 명시된 수치와 정책 제언은 현장 상황과 일부 상이할 수 있으므로, 최종 판단 시 현장 실무 검토가 필요합니다.
            </div>
            
            <script>
                // 이미지가 모두 로드된 후 인쇄 다이얼로그 호출
                window.onload = function() {
                    setTimeout(() => {
                        window.print();
                    }, 500);
                }
            </script>
        </body>
        </html>
    \`);
    printWindow.document.close();
}
`;
    fs.writeFileSync('SIGMA_SIM/js/data.js', dataJs, 'utf8');
    console.log('printAIReport appended to data.js');
} else {
    console.log('printAIReport already exists.');
}
