const fs = require('fs');
let c = fs.readFileSync('SIGMA_SIM/js/phase.js', 'utf8');

const regexHead = /<tr style="background: rgba\(255,255,255,0\.05\);">\s*<th style="padding: 2px 4px; border-bottom: 1px solid rgba\(255,255,255,0\.08\); width: 30px; color: #94a3b8;">#<\/th>\s*\$\{dayPlanIndices\.map\(idx => `\s*<th colspan="3" onclick="changeJunctionDayType\(\$\{idx\}\)" style="padding: 2px 4px; border-bottom: 1px solid rgba\(255,255,255,0\.08\); border-left: 1px solid rgba\(255,255,255,0\.08\); color: \$\{dayIdx === idx \? 'var\(--accent\)' : '#94a3b8'\}; cursor: pointer; font-weight: bold; background: \$\{dayIdx === idx \? 'rgba\(241,196,15,0\.05\)' : 'transparent'\};">\s*\$\{DAY_LABELS\[idx\]\}\s*<\/th>\s*`\)\.join\(''\)\}\s*<\/tr>\s*<tr style="background: rgba\(255,255,255,0\.03\);">\s*<th style="padding: 4px; border-bottom: 1px solid rgba\(255,255,255,0\.08\);"><\/th>\s*\$\{dayPlanIndices\.map\(idx => `\s*<th style="padding: 4px; border-bottom: 1px solid rgba\(255,255,255,0\.08\); border-left: 1px solid rgba\(255,255,255,0\.08\); font-weight: normal; color: #94a3b8; font-size: 9px;">TIME<\/th>\s*<th style="padding: 4px; border-bottom: 1px solid rgba\(255,255,255,0\.08\); font-weight: normal; color: #94a3b8; font-size: 9px;">CYC<\/th>\s*<th style="padding: 4px; border-bottom: 1px solid rgba\(255,255,255,0\.08\); font-weight: normal; color: #94a3b8; font-size: 9px;">IDX<\/th>\s*`\)\.join\(''\)\}\s*<\/tr>/g;

console.log("Head match:", (c.match(regexHead) || []).length);

const regexBody = /return `\s*<td class="phase-tod-cell" data-drop-day="\$\{idx\}" data-drop-slot="\$\{rIdx\}" onclick="selectTodPlanCell\(\$\{idx\}, \$\{rIdx\}\)" style="padding: 2px; border-left: 1px solid rgba\(255,255,255,0\.05\); background: \$\{bg\}; cursor: pointer; position: relative;">\s*<div draggable="true" ondragstart="window\.handlePhaseTodDragStart\(event, \$\{idx\}, \$\{rIdx\}\)" style="cursor: grab; color: #555; position: absolute; left: 1px; top: 2px; font-size: 10px; padding: 2px; z-index: 10;" title="드래그하여 스케줄 복사">⠿<\/div>\s*<input type="text" data-day="\$\{idx\}" data-slot="\$\{rIdx\}" data-field="time" class="sigma-input \$\{hCls\}" value="\$\{hVal\}" placeholder="--:--" style="\$\{inputStyle\} color:\$\{fontColor\}; padding-left: 10px; width: calc\(100% - 10px\);" onchange="handleTodPlanEdit\(\$\{idx\}, \$\{rIdx\}, 'time', this\.value\)">\s*<\/td>\s*<td class="phase-tod-cell" data-drop-day="\$\{idx\}" data-drop-slot="\$\{rIdx\}" onclick="selectTodPlanCell\(\$\{idx\}, \$\{rIdx\}\)" style="padding: 2px; background: \$\{bg\}; cursor: pointer;">\s*<input type="number" data-day="\$\{idx\}" data-slot="\$\{rIdx\}" data-field="cycle" class="sigma-input \$\{cycleCls\}" value="\$\{cycleVal\}" placeholder="-" style="\$\{inputStyle\} color:\$\{fontColor\};" onchange="handleTodPlanEdit\(\$\{idx\}, \$\{rIdx\}, 'cycle', this\.value\)">\s*<\/td>\s*<td class="phase-tod-cell" data-drop-day="\$\{idx\}" data-drop-slot="\$\{rIdx\}" onclick="selectTodPlanCell\(\$\{idx\}, \$\{rIdx\}\)" style="padding: 2px; background: \$\{bg\}; font-weight: bold; cursor: pointer;">\s*<input type="number" data-day="\$\{idx\}" data-slot="\$\{rIdx\}" data-field="idx" class="sigma-input \$\{idxCls\}" value="\$\{idxVal\}" placeholder="-" style="\$\{inputStyle\} color:\$\{fontColor\};" onchange="handleTodPlanEdit\(\$\{idx\}, \$\{rIdx\}, 'idx', this\.value\)">\s*<\/td>\s*`;/g;

console.log("Body match:", (c.match(regexBody) || []).length);
