const fs = require('fs');

// 1. Update index.html to add marked.js
let html = fs.readFileSync('SIGMA_SIM/index.html', 'utf8');
if (!html.includes('marked.min.js')) {
    html = html.replace('<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>', '<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>\n    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>');
    fs.writeFileSync('SIGMA_SIM/index.html', html, 'utf8');
    console.log('marked.js added to index.html');
}

// 2. Update data.js
let dataJs = fs.readFileSync('SIGMA_SIM/js/data.js', 'utf8');

const oldRenderBlockRegex = /\/\/ 렌더링 지연 \([\s\S]*?\}, 500\);/;

const newRenderBlock = `// 렌더링 지연 (애니메이션이 100% 차는 것을 보여주기 위함)
        setTimeout(() => {
            // marked.js를 활용한 마크다운 파싱 (테이블 등 완벽 지원)
            let formattedText = marked.parse(data.report);
            
            // 다크 테마 표/텍스트 최적화를 위한 래퍼 추가
            formattedText = \`<div class="ai-report-markdown">\${formattedText}</div>\`;
            
            // 원본 텍스트(출력용) 전역 저장
            window.__lastAIReportHTML = formattedText;
            window.__lastAIReportTitle = \`\${baseName} vs \${targetName} 교통운영 통계 분석 리포트\`;
            
            content.innerHTML = \`
                <div style="display: flex; justify-content: flex-end; gap: 10px; margin-bottom: 15px;">
                    <button onclick="printAIReport()" style="background: rgba(255,183,77,0.1); border: 1px solid #ffb74d; color: #ffb74d; padding: 4px 12px; border-radius: 4px; font-size: 11px; cursor: pointer; display: flex; align-items: center; gap: 4px;">🖨️ PDF 출력</button>
                    <button onclick="generateAIReport()" style="background: none; border: 1px solid #4a90e2; color: #4a90e2; padding: 4px 12px; border-radius: 4px; font-size: 11px; cursor: pointer; display: flex; align-items: center; gap: 4px;">🔄 다시 분석하기</button>
                </div>
                \${formattedText}
            \`;
        }, 500);`;

if (dataJs.match(oldRenderBlockRegex)) {
    dataJs = dataJs.replace(oldRenderBlockRegex, newRenderBlock);
} else {
    console.log('Failed to find old render block');
}

// Add CSS for markdown tables in dark mode and the print function
if (!dataJs.includes('printAIReport()')) {
    dataJs += `

// ── [신규] AI 리포트 인쇄/PDF 출력 함수 ──
function printAIReport() {
    if (!window.__lastAIReportHTML) return;
    
    const printWindow = window.open('', '_blank', 'width=800,height=900');
    printWindow.document.write(\`
        <html>
        <head>
            <title>SIGMA AI Report - \${window.__lastAIReportTitle}</title>
            <style>
                @import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css');
                body {
                    font-family: 'Pretendard', sans-serif;
                    line-height: 1.6;
                    color: #333;
                    padding: 40px;
                    background: #fff;
                }
                h1, h2, h3 { color: #111; margin-top: 1.5em; border-bottom: 2px solid #eee; padding-bottom: 5px; }
                h4 { color: #444; margin-top: 1.2em; }
                table {
                    width: 100%;
                    border-collapse: collapse;
                    margin: 20px 0;
                    font-size: 12px;
                }
                th, td {
                    border: 1px solid #ccc;
                    padding: 8px 12px;
                    text-align: left;
                }
                th {
                    background-color: #f5f5f5;
                    font-weight: bold;
                    color: #222;
                }
                li { margin-bottom: 5px; }
                strong { color: #000; font-weight: 700; }
                .report-header { text-align: center; margin-bottom: 40px; }
                .report-header h1 { border: none; margin-bottom: 10px; }
                .report-header .meta { color: #777; font-size: 12px; }
                
                @media print {
                    body { padding: 0; }
                    @page { margin: 15mm; }
                }
            </style>
        </head>
        <body>
            <div class="report-header">
                <h1>교통 신호운영 통계 분석 리포트</h1>
                <div class="meta">\${window.__lastAIReportTitle} | Generated by SIGMA AI</div>
            </div>
            \${window.__lastAIReportHTML}
            <script>
                window.onload = function() {
                    window.print();
                    // window.close(); // Optional: close after print dialog
                }
            </script>
        </body>
        </html>
    \`);
    printWindow.document.close();
}
`;
}

fs.writeFileSync('SIGMA_SIM/js/data.js', dataJs, 'utf8');
console.log('data.js updated with marked.js parsing and print function');

// 3. Add custom css for the markdown renderer inside the dark UI
let css = fs.readFileSync('SIGMA_SIM/css/panels.css', 'utf8');
if (!css.includes('.ai-report-markdown')) {
    css += `

/* AI Report Markdown Styles (Dark Theme) */
.ai-report-markdown table {
    width: 100%;
    border-collapse: collapse;
    margin: 15px 0;
    font-size: 12px;
    background: rgba(0,0,0,0.2);
}
.ai-report-markdown th, .ai-report-markdown td {
    border: 1px solid rgba(255,255,255,0.15);
    padding: 8px 10px;
}
.ai-report-markdown th {
    background: rgba(100, 181, 246, 0.1);
    color: #90caf9;
    font-weight: bold;
    text-align: left;
}
.ai-report-markdown td {
    color: #e0e0e0;
}
.ai-report-markdown h3 {
    color: #90caf9;
    margin-top: 25px;
    margin-bottom: 10px;
    border-bottom: 1px solid rgba(144, 202, 249, 0.2);
    padding-bottom: 5px;
    font-size: 16px;
}
.ai-report-markdown h4 {
    color: #81d4fa;
    margin-top: 15px;
    margin-bottom: 8px;
    font-size: 14px;
}
.ai-report-markdown strong {
    color: #ffb74d;
}
.ai-report-markdown ul {
    padding-left: 20px;
}
.ai-report-markdown li {
    margin-bottom: 6px;
}
`;
    fs.writeFileSync('SIGMA_SIM/css/panels.css', css, 'utf8');
    console.log('CSS updated');
}

